src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Regex(
        pattern: '/\d/',
        match: false,
        message: 'Your name cannot contain a number',
    )]
    private ?string $name = null;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\LessThanOrEqual(value: "-10 years", message: "User must be at least 10 years old")]
    #[Assert\LessThanOrEqual(value: "today", message: "Birth date cannot be in the future")]
    private ?\DateTimeInterface $birth_day = null;

    #[ORM\Column(type: Types::SMALLINT)]
    #[Assert\Choice([0, 1, 2, 3])]
    private ?int $gender = null;

    /**
     * @var Collection<int, Workout>
     */
    #[ORM\OneToMany(targetEntity: Workout::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $workouts;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $role = null;

    public function __construct()
    {
        $this->workouts = new ArrayCollection();
    }

//    #[Assert\IsTrue(message: 'The password cannot match your name')]
//    public function isPasswordSafe(): bool
//    {
//        return $this->name !== $this->password;
//    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getBirthDay(): ?\DateTimeInterface
    {
        return $this->birth_day;
    }

    public function setBirthDay(\DateTimeInterface $birth_day): static
    {
        $this->birth_day = $birth_day;

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(int $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection<int, Workout>
     */
    public function getWorkouts(): Collection
    {
        return $this->workouts;
    }

    public function addWorkout(Workout $workout): static
    {
        if (!$this->workouts->contains($workout)) {
            $this->workouts->add($workout);
            $workout->setUser($this);
        }

        return $this;
    }

    public function removeWorkout(Workout $workout): static
    {
        if ($this->workouts->removeElement($workout)) {
            // set the owning side to null (unless already changed)
            if ($workout->getUser() === $this) {
                $workout->setUser(null);
            }
        }

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(?string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getRoles(): array
    {
        $roles=[];
        // TODO: Implement getRoles() method.
        return array_unique($roles);
    }

    public function eraseCredentials(): void
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
        // TODO: Implement getUserIdentifier() method.
    }
}

src/Form/Type/UserType.php
<?php

namespace App\Form\Type;

use App\Entity\Exercise;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void{

        $builder
            ->add('name', TextType::class)
            ->add('email', EmailType::class)
            ->add('password', PasswordType::class)
            ->add('birth_day', BirthdayType::class)
            ->add('gender', ChoiceType::class, [
                'choices'  => [
                'Male' => 0,
                'Female' => 1,
                'Other' => 2,
                'Prefer not to say'=>3,
                    ]
            ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\Type\EditUserType;
use App\Form\Type\SignInType;
use App\Form\Type\UserType;
use App\Repository\ExerciseRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class UserController extends AbstractController
{
    public function __construct(
        private Security $security,
    ){
    }

    #[Route('/users', name: 'show-users', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user=$this->security->getUser();
        if($user->getRole()=='user'){
            $users = $userRepository->findBy(['role' => 'trainer']);
        }else{
            $users = $userRepository->findAll();
        }
        return $this->render('user/showUsers.html.twig', [
            'controller_name' => 'UserController',
            'users' => $users,
            'actualUser'=>$user,
        ]);
    }

    #[Route('/users/{id}', name: 'get-user', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(int $id, UserRepository $userRepository): Response
    {
        $user = $userRepository->find($id);
        if (!$user) {
            throw $this->createNotFoundException('No user found for id ' . $id);
        }
        return $this->render('user/showUser.html.twig', [
            'user' => $user,
        ]);
    }


    #[Route('/users/{id}/edit', name: 'edit-user', methods: ['GET'])]
    public function edit(int $id, UserRepository $userRepository): Response
    {
        $user=$userRepository->findUserById($id);

        $form = $this->createForm(EditUserType::class, $user,[
            'action' => $this->generateUrl('update-user', ['id'=>$id]),
            'method' => 'PATCH',]);
        return $this->render('user/editUser.html.twig', [
            'form' => $form,
            'user'=>$user,
        ]);
    }

    #[Route('/users/{id}', name: 'update-user', methods: ['PATCH'])]
    public function update(int $id, Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $user = $userRepository->findUserById($id);

        $form = $this->createForm(EditUserType::class, $user, [
            'method' => 'PATCH',
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash('success', 'User Edited!');
            return $this->redirectToRoute('show-users');
        }
        return $this->render('user/editUser.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/user/{id}', name: 'delete-user', methods: ['GET','DELETE'])]
    public function delete(int $id, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $user=$userRepository->findUserById($id);
        $entityManager->remove($user);
        $entityManager->flush();
        return $this->redirectToRoute('show-users');
    }


}

templates/user/editUser.html.twig
{% extends '/base.html.twig' %}
{% block title %}User edit{% endblock %}
{% block content%}
    <div class="container mt-4">
    <div class="row justify-content-center">

    <div class="col-md-6 mt-5">
    <div class="text-center">
        <h1>Edit the user</h1>
    </div>
    <div class="card shadow-sm">
    <div class="card-body">
        {{ form_start(form) }}
        {{ form_row(form.name)}}
        {{ form_row(form.birth_day) }}
        {{ form_row(form.gender) }}
        <button type="submit" class="btn btn-primary">Edit</button>
        {{ form_end(form) }}
        <a href="{{  path('delete-user', { 'id': user.id }) }}" class="btn btn-secondary mt-2">Delete</a>
    </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/user/showUser.html.twig
{% extends '/base.html.twig' %}

{% block title %}Account information{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">User details</h1>
        <div class="row justify-content-center">
                    <div class="card shadow-sm">
                        <div class="card-body d-flex justify-content-between align-items-center">
                            <div>
                                <h2 class="card-title mb-1">{{ user.name }}</h2>
                                <p class="card-text mb-1"><strong>Email:</strong> {{ user.email }}</p>
                                <p class="card-text mb-1"><strong>Role:</strong> {{ user.role }}</p>
                                <p class="card-text mb-1"><strong>Birthday:</strong> {{ user.birthDay|date('d-m-Y') }}</p>
                                <p class="card-text mb-0"><strong>Gender:</strong> {{ gender_map[user.gender]|default('Unknown') }}</p>
                            </div>
                        </div>
                    </div>
        </div>
    </div>
{% endblock %}

templates/user/showUsers.html.twig
{% extends '/base.html.twig' %}

{% block title %}Community{% endblock %}

{% block body %}
    <div class="container custom-mt">
        <h1 class="text-center mb-4">Our Community</h1>
        <div class="row justify-content-center">
            {% if is_granted('IS_AUTHENTICATED_FULLY') and actualUser.role=='trainer' %}
            <div class="col-10 mb-3">
                <a href="{{  path('app_register',{'role':'user'})}}" class="btn btn-secondary mt-3 m-md-2"><svg xmlns="http://www.w3.org/2000/svg" width="29" height="29" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
                        <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/>
                        <path d="M8.256 14a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1z"/>
                    </svg></a>
            </div>
            {% endif %}
            {% for user in users %}
                <div class="col-10 mb-3">
                    <div class="card shadow-sm">
                        <div class="card-body d-flex justify-content-between align-items-center">
                            <div>
                                <h2 class="card-title mb-1">{{ user.name }}</h2>
                                <p class="card-text mb-1"><strong>Email:</strong> {{ user.email }}</p>
                                <p class="card-text mb-1"><strong>Role:</strong> {{ user.role }}</p>
                            </div>
                            {% if is_granted('IS_AUTHENTICATED_FULLY') and actualUser.role=='trainer' %}
                                <a href="{{ path('edit-user', { 'id': user.id }) }}" class="btn btn-primary ml-auto">Edit</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/user/signUp.html.twig
{% extends '/base.html.twig' %}

{% block title %}Sign Up{% endblock %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}


{% block content %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-3">
            <h1>Sign Up</h1>
            {{ form_start(form) }}
                {{ form_row(form.name) }}
                {{ form_row(form.email) }}
                {{ form_row(form.password) }}
                {{ form_row(form.birth_day) }}
                {{ form_row(form.gender) }}
                <button type="submit" class="btn btn-primary">Sign Up</button>
                <a href="{{ path('sign-in') }}">Already have an account? Sign In</a>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}