src/Entity/Exercise.php
<?php

namespace App\Entity;

use App\Repository\ExerciseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ExerciseRepository::class)]
class Exercise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 4)]
    #[Assert\Regex(
        pattern: '/\d/',
        match: false,
        message: 'The name cannot contain a number',
    )]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Url]
    private ?string $video_link = null;

    #[ORM\ManyToOne(inversedBy: 'exercises')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Type $type = null;

    /**
     * @var Collection<int, ExerciseLog>
     */
    #[ORM\OneToMany(targetEntity: ExerciseLog::class, mappedBy: 'exercise', orphanRemoval: true)]
    private Collection $exerciseLogs;

    public function __construct()
    {
        $this->exerciseLogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getVideoLink(): ?string
    {
        return $this->video_link;
    }

    public function setVideoLink(?string $video_link): static
    {
        $this->video_link = $video_link;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, ExerciseLog>
     */
    public function getExerciseLogs(): Collection
    {
        return $this->exerciseLogs;
    }

    public function addExerciseLog(ExerciseLog $exerciseLog): static
    {
        if (!$this->exerciseLogs->contains($exerciseLog)) {
            $this->exerciseLogs->add($exerciseLog);
            $exerciseLog->setExercise($this);
        }

        return $this;
    }

    public function removeExerciseLog(ExerciseLog $exerciseLog): static
    {
        if ($this->exerciseLogs->removeElement($exerciseLog)) {
            // set the owning side to null (unless already changed)
            if ($exerciseLog->getExercise() === $this) {
                $exerciseLog->setExercise(null);
            }
        }

        return $this;
    }
}

src/Entity/ExerciseLog.php
<?php

namespace App\Entity;

use App\Repository\ExerciseLogRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExerciseLogRepository::class)]
class ExerciseLog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'exerciseLogs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Workout $workout = null;

    #[ORM\ManyToOne(inversedBy: 'exerciseLogs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Exercise $exercise = null;

    #[ORM\Column]
    private ?int $nr_reps = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $duration = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_time = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getWorkout(): ?Workout
    {
        return $this->workout;
    }

    public function setWorkout(?Workout $workout): static
    {
        $this->workout = $workout;

        return $this;
    }

    public function getExercise(): ?Exercise
    {
        return $this->exercise;
    }

    public function setExercise(?Exercise $exercise): static
    {
        $this->exercise = $exercise;

        return $this;
    }

    public function getNrReps(): ?int
    {
        return $this->nr_reps;
    }

    public function setNrReps(int $nr_reps): static
    {
        $this->nr_reps = $nr_reps;

        return $this;
    }

    public function getDuration(): ?\DateTimeInterface
    {
        return $this->duration;
    }

    public function setDuration(\DateTimeInterface $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTimeInterface $start_time): static
    {
        $this->start_time = $start_time;

        return $this;
    }
}

src/Entity/Workout.php
<?php

namespace App\Entity;

use App\Repository\WorkoutRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WorkoutRepository::class)]
class Workout
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'workouts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    /**
     * @var Collection<int, ExerciseLog>
     */
    #[ORM\OneToMany(targetEntity: ExerciseLog::class, mappedBy: 'workout', orphanRemoval: true)]
    private Collection $exerciseLogs;

    #[ORM\ManyToOne(inversedBy: 'workouts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Type $type = null;


    public function __construct()
    {
        $this->exerciseLogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection<int, ExerciseLog>
     */
    public function getExerciseLogs(): Collection
    {
        return $this->exerciseLogs;
    }

    public function addExerciseLog(ExerciseLog $exerciseLog): static
    {
        if (!$this->exerciseLogs->contains($exerciseLog)) {
            $this->exerciseLogs->add($exerciseLog);
            $exerciseLog->setWorkout($this);
        }

        return $this;
    }

    public function removeExerciseLog(ExerciseLog $exerciseLog): static
    {
        if ($this->exerciseLogs->removeElement($exerciseLog)) {
            // set the owning side to null (unless already changed)
            if ($exerciseLog->getWorkout() === $this) {
                $exerciseLog->setWorkout(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/Type/WorkoutType.php
<?php

namespace App\Form\Type;

use App\Entity\Type;
use App\Entity\Workout;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkoutType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void{

        $builder
            ->add('name', TextType::class)
            ->add('type', EntityType::class, [
                'class' => Type::class,
                'choice_label' => 'name',
                'placeholder' => 'Choose a type',
            ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Workout::class,
        ]);
    }
}

src/Controller/WorkoutController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Workout;
use App\Form\Type\EditWorkoutType;
use App\Form\Type\UserType;
use App\Form\Type\WorkoutType;
use App\Repository\ExerciseLogRepository;
use App\Repository\UserRepository;
use App\Repository\WorkoutRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class WorkoutController extends AbstractController
{

    public function __construct(
        private Security $security,
    ){
    }

    #[Route('/workouts', name: 'show-workouts', methods: ['GET'])]
    public function index(WorkoutRepository $workoutRepository): Response
    {

        $user=$this->security->getUser();
        $workouts = $workoutRepository->findAll();
        return $this->render('workout/showWorkouts.html.twig', [
            'controller_name' => 'WorkoutController',
            'workouts' => $workouts,
            'user' => $user,
        ]);
    }

    #[Route('/workouts/{workoutId}/start', name: 'start-workout', methods: ['GET'])]
    public function startWorkout(int $workoutId, ExerciseLogRepository $exerciseLogRepository): Response
    {

        $exerciseLogs = $exerciseLogRepository->findByWorkoutId($workoutId);

        return $this->render('workout/startWorkout.html.twig', [
            'exerciseLogs' => $exerciseLogs,
        ]);
    }

    #[Route('/workouts/new', name: 'new-workout', methods: ['GET'])]
    public function new(): Response
    {
        $workout = new Workout();

        $form = $this->createForm(WorkoutType::class, $workout,[
            'action' => $this->generateUrl('create-workout'),
            'method' => 'POST',
        ]);


        return $this->render('workout/addWorkout.html.twig', [
            'form' => $form,
        ]);
    }


    #[Route('/workout', name: 'create-workout', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $workout = new Workout();

        $form = $this->createForm(WorkoutType::class, $workout);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $workout= $form->getData();
            $user=$this->security->getUser();
            $workout->setUser($user);
            $workout->setDate(new \DateTime());
            $entityManager->persist($workout);
            $entityManager->flush();
//            $this->addFlash('success', 'Workout added successfully!');
            return $this->redirectToRoute('show-workouts');
        }

        return $this->render('workout/addWorkout.html.twig', [
            'form' => $form,
        ]);

    }


    #[Route('/workouts/{id}/edit', name: 'edit-workout', methods: ['GET'])]
    public function edit(int $id, WorkoutRepository $workoutRepository): Response
    {
        $workout = $workoutRepository->find($id);
        if (!$workout) {
            throw $this->createNotFoundException('No workout found for id ' . $id);
        }
        $form = $this->createForm(WorkoutType::class, $workout,[
            'action' => $this->generateUrl('update-workout', ['id'=>$id]),
            'method' => 'PATCH',]);
        return $this->render('workout/editWorkout.html.twig', [
            'form' => $form,
            'workout' => $workout,
        ]);
    }

    #[Route('/workouts/{id}', name: 'update-workout', methods: ['PATCH'])]
    public function update(int $id, Request $request, EntityManagerInterface $entityManager, WorkoutRepository $workoutRepository): Response
    {
        $workout = $workoutRepository->find($id);
        if (!$workout) {
            throw $this->createNotFoundException('No workout found for id ' . $id);
        }

        $form = $this->createForm(WorkoutType::class, $workout, [
            'method' => 'PATCH',
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $entityManager->persist($user);
            $entityManager->flush();
            $this->addFlash('success', 'Workout Edited!');
            return $this->redirectToRoute('show-workouts');
        }
        return $this->render('workout/editWorkout.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/workouts/{id}', name: 'delete-workout', methods: ['GET','DELETE'])]
    public function delete(int $id, EntityManagerInterface $entityManager,  WorkoutRepository $workoutRepository): Response
    {
        $workout = $workoutRepository->find($id);
        $entityManager->remove($workout);
        $entityManager->flush();
        return $this->redirectToRoute('show-workouts');
    }

}

templates/workout/addWorkout.html.twig
{% extends '/base.html.twig' %}

{% block title %}New Workout{% endblock %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}


{% block content %}

    <div class="container mt-4">
            <div class="col-md-3">
                <h1>New Workout</h1>
                {{ form_start(form) }}
                {{ form_row(form.name) }}
                {{ form_row(form.type) }}
                <button type="submit" class="btn btn-primary">Save</button>
                {{ form_end(form) }}
            </div>
    </div>
{% endblock %}

templates/workout/editWorkout.html.twig
{% extends '/base.html.twig' %}
{% block title %}Workout edit{% endblock %}
{% block content%}
    <div class="container mt-4">

        <h1>Edit workout</h1>
        <p><strong>Creation date: </strong>{{ workout.date|date('d-m-Y')}}</p>
        {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.type) }}
        <button type="submit" class="btn btn-primary">Save</button>
        {{ form_end(form) }}
        <a href="{{  path('delete-workout', { 'id': workout.id }) }}" class="btn btn-secondary mt-2">Delete</a>
    </div>
{% endblock %}

templates/workout/showWorkouts.html.twig
{% extends '/base.html.twig' %}

{% block title %}Workouts{% endblock %}

{% block body %}
    <div class="container custom-mt">
        <h1 class="text-center mb-4">Workout List</h1>
        <div class="row justify-content-center">
            {% if is_granted('IS_AUTHENTICATED_FULLY') and user.role=='trainer' %}
            <div class="col-10 mb-3">
                <a href="{{  path('new-workout')}}" class="btn btn-secondary mt-3 m-md-2">Add new workout</a>
            </div>
            {% endif %}
            {% for workout in workouts %}
                <div class="col-10 mb-3">
                    <div class="card shadow-sm">
                        <div class="card-body d-flex justify-content-between align-items-center">
                            <div>
                                <h2 class="card-title mb-1">{{ workout.name }}</h2>
                                <p class="card-text mb-1"><strong>Created by:</strong> {{ workout.user.name }}</p>
                                <p class="card-text mb-1"><strong>Date created:</strong> {{ workout.date|date('d-m-Y') }}</p>
                                <p class="card-text mb-0"><strong>Type:</strong> {{ workout.type.name }}</p>
                            </div>
                            <a href="{% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                                {{ path('show-exercise-logs', { 'workoutId': workout.id}) }}{% else%}
                                                {{ path('app_login')}}{% endif %}" class="btn btn-primary ml-auto">View</a>
                            {% if is_granted('IS_AUTHENTICATED_FULLY') and workout.user.email==user.email and user.role=='trainer' %}
                            <a href="{{ path('edit-workout', { 'id': workout.id}) }}" class="btn btn-primary ml-auto">Edit</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/workout/startWorkout.html.twig
{% extends '/base.html.twig' %}

{% block title %}Start Workout{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Workout: {{ exerciseLogs[0].workout.name }}</h1>
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-interval="false">
            <div class="carousel-inner">
                {% for exerciseLog in exerciseLogs %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <div class="card shadow-sm carousel-card">
                            <div class="card-body d-flex">
                                <div class="left-content">
                                    <h2 class="card-title mb-1">{{ exerciseLog.exercise.name }}</h2>
                                    <p class="card-text mb-1"><strong>Type:</strong> {{ exerciseLog.exercise.type.name }}</p>
                                    <p class="card-text mb-1"><strong>Reps:</strong> {{ exerciseLog.nrReps }}</p>
                                    <div id="timer-{{ loop.index }}" class="timer-container">
                                        <span class="timer">Time: <strong>{{ exerciseLog.duration|date('i:s') }}</strong></span>
                                    </div>
                                    <button class="btn btn-secondary mt-2 start-exercise-button" data-index="{{ loop.index }}" data-duration="{{ exerciseLog.duration|date('U') - '1970-01-01 00:00:00'|date('U') }}">Start</button>
                                    <button class="btn btn-secondary mt-2 pause-exercise-button" data-index="{{ loop.index }}" style="display: none;">Pause </button>
                                </div>
                                <div class="right-content d-flex align-items-center justify-content-center">
                                    <div class="embed-responsive embed-responsive-16by9 h-100">
                                        {% if exerciseLog.exercise.videoLink %}
                                            {% set embedUrl = exerciseLog.exercise.videoLink|replace({'watch?v=': 'embed/'})|split('&')[0] %}
                                            <iframe class="embed-responsive-item" src="{{ embedUrl }}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                        {% else %}
                                            <p class="text-center my-3">No video available</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>

    <style>
        .carousel-control-prev-icon,
        .carousel-control-next-icon {
            background-color: #7465b5;
            border-radius: 50%;
        }

        .timer-container {
            display: flex;
            margin-top: 15px;
        }

        .timer {
            font-size: 1.5rem;
            color: #ffffff;
            background-color: #9287bf;
            padding: 10px 20px;
            border-radius: 5px;
            font-weight: bold;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .carousel-control-prev,
        .carousel-control-next {
            width: 5%;
        }

        .carousel-card {
            width: 70%;
            height: 40vh;
            margin: 0 auto;
        }

        .card-body {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .left-content {
            flex: 1;
            padding-right: 20px;
        }

        .right-content {
            flex: 0 0 150px;
        }

        .btn.pause-exercise-button {
            background-color: #53abbd;
            border-color: #53abbd;
            color: #fff;
        }

        .btn.resume-exercise-button {
            background-color: #53abbd;
            border-color: #53abbd;
            color: #fff;
        }
    </style>

    <script>
        document.querySelectorAll('.start-exercise-button').forEach(button => {
            button.addEventListener('click', function() {
                let index = this.getAttribute('data-index');
                let duration = parseInt(this.getAttribute('data-duration'));
                let timerContainer = document.getElementById(`timer-${index}`);
                let timer = timerContainer.querySelector('.timer strong');
                let pauseButton = document.querySelector(`.pause-exercise-button[data-index="${index}"]`);
                let startButton = this;

                startButton.style.display = 'none';
                pauseButton.style.display = 'inline-block';

                let countdown = setInterval(() => {
                    if (!timerContainer.getAttribute('data-paused')) {
                        let minutes = Math.floor(duration / 60);
                        let seconds = duration % 60;
                        timer.textContent = `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
                        duration--;

                        if (duration < 0) {
                            clearInterval(countdown);
                            pauseButton.style.display = 'none';
                        }
                    }
                }, 1000);

                pauseButton.addEventListener('click', function() {
                    if (timerContainer.getAttribute('data-paused')) {
                        timerContainer.removeAttribute('data-paused');
                        this.textContent = 'Pause';
                        this.classList.remove('resume-exercise-button');
                        this.classList.add('pause-exercise-button');
                    } else {
                        timerContainer.setAttribute('data-paused', 'true');
                        this.textContent = 'Resume';
                        this.classList.remove('pause-exercise-button');
                        this.classList.add('resume-exercise-button');
                    }
                });
            });
        });
    </script>
{% endblock %}